name: Build docker image

on: 
  push: 
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request: 
    branches: [ "master" ]

env: 
  ALPINE_VERSION: ${{ secrets.ALPINE_VERSION }}
  DOCKER_IMAGE_TAGS: ${{ secrets.DOCKER_IMAGE_TAGS }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: ${{ github.repository }}
  DOCKER_REGISTRY: ghcr.io

jobs: 
  build-alpine-3_18: 
    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: write
      id-token: write
  
  steps: 
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with: 
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions
      with: 
        version: ${{ env.ALPINE_VERSION }}
        tags: ${{ env.DOCKER_IMAGE_TAGS }}
        platform: linux/amd64,linux/arm64